### ISSUE TITLE
ImportError: libGL.so.1 cannot be opened in Docker container

### ISSUE THREAD

**Issue by dimitri009** [swiss-ai-center/image-rotate-service#11]
@rmarquis 

When running the application in a Docker container, I encounter an ImportError related to OpenCV. The error message indicates that the required shared library libGL.so.1 is missing.

Steps to Reproduce

    Build the Docker image using the following command:

       docker compose build 

Run the Docker container:

        docker compose up -d

Observe the logs which produce the following error message:

      
![Screenshot 2024-11-04 162713](https://github.com/user-attachments/assets/fc9b5354-b82c-43e3-8060-71ad30d10e01)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by rmarquis** [comment]
Thank for the report, I'm looking into it.

**Comment by rmarquis** [comment]
I cannot reproduce, but this might be related to the need of having GL support available on the host (and not only in the container).

Instruction to get this running varies according to your host distribution.
If you're using Ubuntu/Debian, try installing `libgl1` or similar. Looking also into `libglvnd` (GL vendor neutral library) might help on other distro too.

**Comment by dimitri009** [comment]
I am on windows, I tried to implement another service too using cv2, everything works perfectly fine on the local IDE but one I try to deploy into the docker I have this error, already tried [1](https://stackoverflow.com/questions/55313610/importerror-libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directo) , [2](https://stackoverflow.com/questions/68215509/importerror-libgl-so-1-when-running-docker-container-with-opencv) , [3](https://stackoverflow.com/questions/72365190/libgl-so-1-cannot-open-shared-object-file-no-such-file-or-directory-even-whe) and [this](https://python1233.rssing.com/chan-44877200/article17518.html) without solving the issue.

**Comment by rmarquis** [comment]
You can (and should) use WSL2 on Windows. This is what I'm doing, it works great with VS Code/PyCharm, and it will save you many headaches.

**Comment by dimitri009** [comment]
I am installing WSL via this command:

        wsl --install
 
 is there any other change should I make after this ?

**Comment by dimitri009** [comment]
I installed 

     wsl --install
     
Ensured Docker Desktop is installed and configured to use WSL 2 as its backend.

Open Docker Desktop, go to **Settings** > **Resources** > WSL **Integration,** and made sure WSL distribution (e.g., Ubuntu) is enabled for integration.

added this line in my Dockerfile 

      RUN apt-get update && apt-get install libgl1
      
Ran the following commands to rebuild and restart your container:

      docker-compose build
      docker-compose up

But I ended with the same error

**Comment by rmarquis** [comment]
I'm afraid I cannot reproduce the issue.

I've tested on a clean Ubuntu-24.04 image in WSL: `wsl --install Ubuntu-24.04`.

Installed `python3.11` and `python3.11-venv` (through the deadsnake ppa), cloned the repo, created the virtual env and activated it, and foillowed the tutorial.

I did install docker in the VM instead of using the Docker Desktop client. I'd suggest to give this a try:

```
sudo apt install docker.io docker-compose-v2
sudo usermod -aG docker $USER
```
You'll need to logout at this point and login again, so group permissions are correctly applied to your user.

After this, `docker compose build` and `docker compose up` should work as expected (at least it does on my machine).

**Comment by dimitri009** [comment]
Sorry but even in the wsl I got the same error. 

    wsl --install Ubuntu-24.04
    sudo add-apt-repository universe
    sudo apt update
    sudo add-apt-repository ppa:deadsnakes/ppa
    sudo apt install python3.11
    sudo apt install python3.11-venv
    python3.11 -m venv venv 
after that I activated the environment 
    sudo apt install docker.io docker-compose
    sudo usermod -aG docker $USER
Followed the tutorials, but it ends with the same error:
    service_1  |   File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    service_1  |     return _bootstrap._gcd_import(name[level:], package, level)
    service_1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    service_1  | ImportError: libGL.so.1: cannot open shared object file: No such file or directory

**Comment by rmarquis** [comment]
What happens if you now install `libgl1` with apt?

**Comment by dimitri009** [comment]
Added in the Dockerfile 

    RUN apt update && apt install --yes ffmpeg libsm6 libxext6 libgl1

It ends with the same error, I really don't understand, there is a problem with cv2, because I implemented 

>    average shade 
>    text summarize 

without problem on my windows

**Comment by dimitri009** [comment]
Hey @rmarquis, we (@andrptrc and me) did the solution 3 from [this](https://python1233.rssing.com/chan-44877200/article17518.html).
It solved the error, I ran the service and it worked.

**Comment by rmarquis** [comment]
Glad you found it! That's a weird one indeed.

For the record, I'll copy the fix here:
```
Solution 3: Install opencv-python-headless
Instead of opencv-python, you could install opencv-python-headless which includes a a precompiled binary wheel with no external dependencies (other than numpy), and is intended for headless environments like Docker.

When compared to python3-opencv this is a much more lightweight package and reduces the docker image size by 700MB.

RUN apt-get update && apt-get install -y opencv-python-headless
RUN pip install opencv-python-headless
```
